.TH GACQUARD "1" "January 2012" "gacquard 1.0" "User Commands"
.SH NAME
gacquard \- Jacquard loom pattern editor
.SH SYNOPSIS
.B gacquard
[filename]
.SH DESCRIPTION
Gacquard allows editing of weaving patterns and can convert the weaving pattern to punch cards needed to operate a Jacquard loom.
.SH AUTHOR
\fBGacquard\fP was written by Andre Masella <andre@masella.name>.
